### ISSUE TITLE
Plugin dependencies broken

### ISSUE THREAD

**Issue by sesquipedality** [lfasci/homeassistant-prometheus-query#15]
Hi, the plugin again became non-functional due to a dependency conflict with the "requests" package.   Fixable by changing the relevant line in manifest.json as follows:

     "requirements": ["prometheus-client==0.9.0", "requests>=2.27.1"],

Hope this is useful.  I have also created a pull request to merge this fix into the main branch.

**Comment by lfasci** [comment]
Thank you very much, I merged your fix today

**Comment by sesquipedality** [comment]
No problem.  Glad it was useful.
