### ISSUE TITLE
Manifest.json is missing version property

### ISSUE THREAD

**Issue by mariwing** [lfasci/homeassistant-prometheus-query#3]
Since Home Assistant 2021.6 it is a requirement that a version property should be included in the manifest.json file.

**Comment by darox** [comment]
So this is probably the reason why this component is broken since then?

**Comment by kquinsland** [comment]
@darox likely, yes. As of now, this repo can't be added via HACS :(

**Comment by lfasci** [comment]
I modified the manifest.json file and changed the folder name, the name must be changed also in home assistant config file.
It's working on my home assitant, open another issue in case of problems

**Comment by darox** [comment]
To what did you change the folder name and manifest?

**Comment by lfasci** [comment]
For the name the change was from prometheus-query to prometheus_query, for the version I changed it to "version": "2021.06.1", I removed an empty row from the manifest.
