### ISSUE TITLE
How to use multiple query sensors.

### ISSUE THREAD

**Issue by rudeboi1992** [lfasci/homeassistant-prometheus-query#7]
I've tried for the life of me to figure it out, but how do we make multiple queries show up as individual sensors?

**Comment by lfasci** [comment]
You have to specify a unique_id here is a fragment of my config

  - platform: prometheus_query
    name: "Temperature Pisa"
    **unique_id: "tempPisa"**
    prometheus_url: http://localhost:9090
    **prometheus_query**: temperature{job="cfrt",location=~"Pisa Fac Agraria.*",province="PI",region="Toscana"}
    unit_of_measurement: "°C"    
  - platform: prometheus_query
    name: "Temperature Cecina"
    **unique_id: "tempCecina"**
    prometheus_url: http://localhost:9090
    **prometheus_query**: temperature{job="cfrt",location=~"Cecina.*",province="LI",region="Toscana"}
    unit_of_measurement: "°C"
  - platform: prometheus_query
    name: "Wind Quercianella"
    **unique_id: "windQuercianella"**
    prometheus_url: http://localhost:9090
    **prometheus_query**: wind_speed{job="cfrt",location="Quercianella",province="LI",region="Toscana"}  * 3.6

I have three entities two for temperature and on for wind.
